# Site settings
title: David Baughman | Front-end Developer
email: hello@dmbaughman.com
description: > # Projects, musings and stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmbaughman.com" # the base hostname & protocol for your site
twitter_username: dmbaughman
github_username:  dmbaughman
collections: 
    - work

# Build settings
markdown: kramdown
exclude:
    - 'node_modules'
    - 'README.md'
    - 'LICENSE'
